apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uw58er0f9-python
  janus-idp.io/tekton: uw58er0f9-python
  backstage.io/kubernetes-id: uw58er0f9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uw58er0f9-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
